{% set name = "shodan" %}
{% set version = "1.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shodan-{{ version }}.tar.gz
  sha256: ebea6dbc1944497e9139263423ea4d103dcd58c085c5ddbf4d6ab1db6eb1d142

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - shodan=shodan.__main__:main

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - certifi
    - python >=3.4
    - click
    - click-plugins
    - xlsxwriter
    - requests >=2.2.1
    - colorama

test:
  source_files:
    - tests
  imports:
    - shodan
  commands:
    - pip check
    - shodan --help
    # Skip test suite becuase it requires Shodan API key
#     - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/achillean/shodan-python
  summary: Python library and command-line utility for Shodan, a search engine for Internet-connected devices.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
